### ISSUE TITLE
UI Translation (Broken Korean lang support)

### ISSUE THREAD

**Issue by Joonie86** [digableinc/tinfoil#18]
I was able to confirm that all the texts are translated for Korean, however it seems to have an issue with a font. all the characters are shown as [] [] as if it's not loading the font from the system.

Could you please investigate this issue when you get a chance? 

https://i.imgur.com/eG8iEwX.png
https://i.imgur.com/25Xfxin.png

**Comment by blawar** [comment]
Oof, I forgot the switch has a different font for korean.  I'll try to load it and push an update.

**Comment by blawar** [comment]
I just committed a new build to master that should fix your issue.  I think Nintendo hates Koreans based on their font support.  Thank you for the bug report.

**Comment by Joonie86** [comment]
Unfortunately, Chinese and Japanese display characters fine while Korean is still broken.
There are like 2 fonts for Chinese (Simplified and Traditional) and 1 dedicated font for Korean only. 
Could you take a look at the issue again when you get a chance? Thanks in advance!

https://cdn.discordapp.com/attachments/491856532510736385/513516028387524609/image0.jpg

**Comment by blawar** [comment]
hello,

the fix is in master, not the release.  please grab the nro from master.

**Comment by blawar** [comment]
feel free to pm me on discord as well
